# .github/workflows/auto-label-needs-ci-approval.yml
name: Auto label for external PRs

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  contents: read
  issues: write   # potrzebne do dodawania/zdjęcia labeli
  pull-requests: write

jobs:
  add-label:
    # Pomiń dla zaufanych autorów (owner/member/collaborator) i dla botów, jeśli chcesz
    if: ${{ !contains(fromJson('["OWNER","MEMBER","COLLABORATOR"]'), github.event.pull_request.author_association)
           && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const label = 'needs-ci-approval';
            try {
              // upewnij się, że label istnieje (jeśli nie, utwórz)
              try {
                await github.request('POST /repos/{owner}/{repo}/labels', {
                  ...context.repo,
                  name: label,
                  color: 'D4C5F9'
                });
              } catch (e) {
                if (e.status !== 422) throw e; // 422 = już istnieje
              }

              // dodaj label do PR (PR to "issue" w API)
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels: [label],
              });
              core.info(`Added '${label}' to PR #${context.issue.number}`);
            } catch (e) {
              core.setFailed(`Failed to label PR: ${e.status || ''} ${e.message}`);
            }
